const levels = {
  1: {
    hint: 'more or less',
    puzzle: [
      ['P1', 'a', 's', ''],
      ['m', '', 'b', 'x'],
      ['r', 'j', 'o', ''],
      ['', 'u', '', 't'],
    ],
    solution: 'about',
    moves: 8,
  },
  2: {
    hint: 'product of 4 and 10',
    puzzle: [
      ['o', 'r', 'f', ''],
      ['', '', '', 't'],
      ['b', 'P1', 'i', 'k'],
      ['w', '', 'y', ''],
    ],
    solution: 'forty',
    moves: 14,
  },
  3: {
    hint: 'v',
    puzzle: [
      ['e', 'f', 'l', '', ''],
      ['', '', '', 'i', ''],
      ['', 'g', '', 'z', ''],
      ['P1', 'j', 'v', 'l', ''],
      ['', '', '', '', 'o'],
    ],
    solution: 'five',
    moves: 15,
  },
  4: {
    hint: 'slice of pie',
    puzzle: [
      ['e', 'g', 'f', 'p', ''],
      ['r', 'c', '', '', ''],
      ['', 'i', 'P1', 'b', 't'],
      ['', 'a', 'n', '', ''],
      ['z', '', '', '', 'o'],
    ],
    solution: 'percent',
    moves: 21,
  },
  5: {
    hint: 'haphazard',
    puzzle: [
      ['', '', '', '', '', ''],
      ['e', 'r', 'c', 'j', 'n', ''],
      ['', '', '', '', '', ''],
      ['P1', '', 'd', '', '', ''],
      ['', 'k', '', 'a', 'h', ''],
      ['', '', '', '', '', ''],
    ],
    solution: 'chance',
    moves: 22,
  },
  6: {
    hint: 'fill in ___ blank',
    puzzle: [
      ['', 'e', 't', '', '', 'P1'],
      ['', '', '', 'r', 'l', ''],
      ['e', 'n', 'h', '', 't', ''],
      ['', '', 't', '', 't', 'g'],
      ['', 'z', '', 'c', '', ''],
      ['', '', '', '', '', ''],
    ],
    solution: 'the',
    moves: 8,
  },
  7: {
    hint: 'tell it to the judge',
    puzzle: [
      ['k', 'j', '', '', 'm', ''],
      ['', '', 't', 'n', '', 'x'],
      ['g', 'h', '', '', '', 'e'],
      ['', '', 'j', 'h', 'f', ''],
      ['u', 'r', '', '', '', ''],
      ['', '', '', 'P1', 'd', ''],
    ],
    solution: 'truth',
    moves: 15,
  },
  8: {
    hint: 'completely asleep',
    puzzle: [
      ['j', '', 'P1', '', 'o', ''],
      ['e', '', 'o', '', 'e', ''],
      ['f', '', 'k', '', 'y', 't'],
      ['o', '', 'p', '', 'x', ''],
      ['h', '', 'd', '', 'c', 'e'],
      ['u', '', 'u', '', 'j', 't'],
    ],
    solution: 'out',
    moves: 6,
  },
  9: {
    hint: 'exists',
    puzzle: [
      ['t', '', 'x', 'd', 'y', 's', 'r'],
      ['', 'm', '', 'l', '', 'h', ''],
      ['z', '', 'i', 'c', '	e	', '', '	j'],
      ['', 'b', '', '', 'u', 't', 'q'],
      ['', '', '', 'f', '', 'g', ''],
      ['o', 'n', 'k', '', 's', '', ''],
      ['i', '', 'w', '', 'v', '', 'P1'],
    ],
    solution: 'is',
    moves: 4,
  },
  10: {
    hint: 'calming when repeated',
    puzzle: [
      ['q', '', '', 'y', 'l', 'e', ''],
      ['h', 'a', '', 'b', 't', '', ''],
      ['g', 'x', 'P1', '', '', 'o', 'z'],
      ['', '', 'p', 'k', 'f', '', 'u'],
      ['', 'w', 'c', '', 'n', '', 'v'],
      ['h', 'i', 'j', '', 'a', 'd', ''],
      ['', '', 's', '', 'm', '', 'r'],
    ],
    solution: 'there',
    moves: 13,
  },
}

export default levels
